<a href="https://colab.research.google.com/github/MichalMichalowski/data-science-cwiczenia/blob/main/Alg_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([2,5])
v1

array([2, 5])

In [3]:
np.linalg.norm(v1)

5.385164807134504

Odległość dwóch punktów w przestrzeni Rn

In [8]:
p = np.array([4,2, 3, 23])
q = np.array([2,8, 9, 1])

np.linalg.norm( p - q )


23.664319132398465

Mnożenie macierzy

In [13]:
m1 = np.array([[2,3],[0,1]])
m2 = np.array([2,1])


np.linalg.norm(np.dot(m2,m1) - m2)

6.324555320336759

Wyznacznik macierzy

In [36]:
np.random.seed(0)

macierz = np.arange(start=np.random.randint(low=3,high=10),stop=np.random.randint(low=30,high=50),step=5, dtype='float')
np.random.shuffle(macierz)
macierz = macierz.reshape(4,2)
print(macierz)

[[37. 17.]
 [12. 27.]
 [42. 22.]
 [ 7. 32.]]


In [40]:
macierz2 = np.array([[2,3,4],[2,4,4],[6,4,5]])

np.linalg.det(macierz2)

-13.999999999999996

Ślad macierzy

In [41]:
np.trace(macierz2)

11

In [42]:
macierz2.T

array([[2, 2, 6],
       [3, 4, 4],
       [4, 4, 5]])