<a href="https://colab.research.google.com/github/MichalMichalowski/data-science-cwiczenia/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [8]:
arr_d = np.array([1,3,5,3,9])
arr_d

array([1, 3, 5, 3, 9])

In [9]:
arr_d.dtype

dtype('int64')

In [11]:
len(arr_d)

5

Tabele 2-wymiarowe

In [16]:
arr_2d = np.array([[1,4],[2,3]])
arr_2d

array([[1, 4],
       [2, 3]])

In [17]:
arr_2d.ndim

2

In [18]:
arr_2d.shape

(2, 2)

Tabele 3-wymiarowe

In [22]:
arr_3d = np.array([[[2,3,4],[5,2,1],[2,8,0]]])
arr_3d.ndim

3

In [27]:
np_array = np.zeros(10, dtype='int64')
np_array[5] = 4
np_array

array([0, 0, 0, 0, 0, 4, 0, 0, 0, 0])

In [35]:
arange_array = np.arange(0,21,2.5,dtype='float')
arange_array.reshape(3,3)

array([[ 0. ,  2.5,  5. ],
       [ 7.5, 10. , 12.5],
       [15. , 17.5, 20. ]])

In [38]:
arr2 = np.arange(2,40, dtype=np.uint8)
arr2.dtype

dtype('uint8')

In [42]:
np.ones(shape=(5,15), dtype=np.uint8)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [43]:
np.full(shape=(6,7), fill_value=25, dtype=np.uint8)

array([[25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25]], dtype=uint8)

In [44]:
np.linspace(1,3,20)

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [76]:
arr_A = np.arange(start=4, stop=np.random.randint(low=10,high=20), dtype='float')
arr_B = np.linspace(start=1, stop=2, num=len(arr_A), dtype='float')

In [77]:
arr_A + arr_B

array([ 5.        ,  6.07692308,  7.15384615,  8.23076923,  9.30769231,
       10.38461538, 11.46153846, 12.53846154, 13.61538462, 14.69230769,
       15.76923077, 16.84615385, 17.92307692, 19.        ])

In [83]:
X = np.array([2,3,4,3]).reshape(2,2)
Y = np.array([4,2,1,8]).reshape(2,2)
print(X)
print(Y)

[[2 3]
 [4 3]]
[[4 2]
 [1 8]]


In [84]:
np.dot(X,Y)

array([[11, 28],
       [19, 32]])

In [85]:
X @ Y

array([[11, 28],
       [19, 32]])

In [86]:
Y @ X

array([[16, 18],
       [34, 27]])